### ISSUE TITLE
Adicionar Pipeline de CI/CD

### ISSUE THREAD

**Issue by LucasOliveiraSimao** [LucasOliveiraSimao/Cabo-Josias-Informa#20]
## Task Description
Configuração de um pipeline de CI/CD (Integração Contínua e Entrega Contínua) para o aplicativo, visando automação de testes, build e deploy.

## Acceptance Criteria

1. [x] Um serviço de CI/CD deve ser configurado para o repositório do aplicativo.
2. [x] O pipeline deve automatizar a execução de testes unitários e de UI.
3. [x] O pipeline deve automatizar o processo de build do aplicativo.
4. [x] O pipeline deve automatizar o deploy para os ambientes de desenvolvimento, staging e produção.
