### ISSUE TITLE
Implementação de Novas Funcionalidades da Versão 1

### ISSUE THREAD

**Issue by LucasOliveiraSimao** [LucasOliveiraSimao/Cabo-Josias-Informa#23]
## Epic Description
Esta epic engloba a implementação de várias novas funcionalidades no aplicativo, visando melhorar a experiência do usuário e aprimorar a sua utilidade. As funcionalidades incluem a integração com o Firebase para recursos como biografia, lista de projetos, agenda de eventos e notificações, além da configuração de um pipeline de CI/CD para automação de testes e deploy contínuo. Também está incluso na epic a criação de diferentes tipos de build (beta e produção) para facilitar o gerenciamento de versões do aplicativo.

## List of Tasks (Complete in order)

1. [x] [Task 1: Adicionar Pipeline de CI/CD](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/20)
2. [x] [Task 2: Subir Versão Beta do App no Google Play Store](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/22)
3. [x] [Task 3: Integrar ao serviço do Firebase](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/15)
4. [x] [Task 4: Lista de Projetos](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/17)
5. [x] [Task 5: Tela de Biografia](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/16)
6. [x] [Task 6: Criar Build Type para Versão Beta e Versão de Produção do Aplicativo](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/22)
7. [x] [Task 7: Feature Agenda de Eventos: Integrar com Firebase](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/18)
8. [x] [Task 8: Feature Notificação: Integrar com Firebase](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/19)
9. [x] [Task 9: Implementar Função de Compartilhamento para Eventos e Projetos](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/31)
