### ISSUE TITLE
Versão 1.1.0

### ISSUE THREAD

**Issue by LucasOliveiraSimao** [LucasOliveiraSimao/Cabo-Josias-Informa#43]
## List of Tasks (Complete in order)

1. [x] [Trocar o ícone do app por outro mais adequado](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/44)
2. [x] [Modificar as cores do app](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/45)
3. [ ] [Adicionar anúncios (ads)](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/46)
