### ISSUE TITLE
Epic Issue Template

### ISSUE THREAD

**Issue by LucasOliveiraSimao** [LucasOliveiraSimao/Cabo-Josias-Informa#8]
### Lista de Tarefas

- [ ] Tarefa 1: [Task Template](https://github.com/LucasOliveiraSimao/Cabo-Josias-Informa/issues/7)
- [ ] Tarefa 2: [Título da Tarefa 2](link para a tarefa)
- [ ] Tarefa 3: [Título da Tarefa 3](link para a tarefa)
- [ ] Tarefa 4: [Título da Tarefa 4](link para a tarefa)
